// SOURCE OF TRUTH (backend copy). This table is duplicated from
// `.\src\data\deliveryRates.ts` because the frontend (Vite) and backend
// (Express) are separate npm packages with no shared module boundary.
// This copy is authoritative for order pricing: the server always
// recomputes deliveryCost from (wilaya, deliveryMethod) itself and never
// trusts a client-submitted price. Keep both copies in sync manually.

export type DeliveryMethod = 'A_DOMICILE' | 'STOP_DESK';

export const WILAYAS = [
  'Alger',
  'Blida',
  "Boumerdès",
  'Tipaza',
  'Chlef',
  'Oum El Bouaghi',
  'Batna',
  'Béjaïa',
  'Bouira',
  'Tlemcen',
  'Tiaret',
  'Tizi Ouzou',
  'Jijel',
  'Sétif',
  'Saïda',
  'Skikda',
  'Sidi Bel Abbès',
  'Annaba',
  'Guelma',
  'Constantine',
  'Médéa',
  'Mostaganem',
  "M'Sila",
  'Mascara',
  'Oran',
  'Bordj Bou Arreridj',
  'El Tarf',
  'Tissemsilt',
  'Khenchela',
  'Souk Ahras',
  'Mila',
  'Aïn Defla',
  'Aïn Témouchent',
  'Relizane',
  'Laghouat',
  'Biskra',
  'Tébessa',
  'Djelfa',
  'Ouargla',
  "El Oued",
  'Ghardaïa',
  'Ouled Djellal',
  'Touggourt',
  "El M'Ghair",
  'El Menia',
  'Timimoun',
  'Bordj Badji Mokhtar',
  'Béni Abbès',
  'Adrar',
  'Béchar',
  'El Bayadh',
  'Naâma',
  'In Salah',
  'In Guezzam',
  'Djanet',
  'Tamanrasset',
  'Illizi',
  'Tindouf',
] as const;

export type Wilaya = typeof WILAYAS[number];

export const DELIVERY_RATES: Record<Wilaya, Record<DeliveryMethod, number>> = {
  'Alger': { A_DOMICILE: 400, STOP_DESK: 400 },
  'Blida': { A_DOMICILE: 650, STOP_DESK: 450 },
  "Boumerdès": { A_DOMICILE: 650, STOP_DESK: 450 },
  'Tipaza': { A_DOMICILE: 650, STOP_DESK: 450 },
  'Chlef': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Oum El Bouaghi': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Batna': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Béjaïa': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Bouira': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Tlemcen': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Tiaret': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Tizi Ouzou': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Jijel': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Sétif': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Saïda': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Skikda': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Sidi Bel Abbès': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Annaba': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Guelma': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Constantine': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Médéa': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Mostaganem': { A_DOMICILE: 750, STOP_DESK: 450 },
  "M'Sila": { A_DOMICILE: 750, STOP_DESK: 450 },
  'Mascara': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Oran': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Bordj Bou Arreridj': { A_DOMICILE: 750, STOP_DESK: 450 },
  'El Tarf': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Tissemsilt': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Khenchela': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Souk Ahras': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Mila': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Aïn Defla': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Aïn Témouchent': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Relizane': { A_DOMICILE: 750, STOP_DESK: 450 },
  'Laghouat': { A_DOMICILE: 950, STOP_DESK: 550 },
  'Biskra': { A_DOMICILE: 950, STOP_DESK: 550 },
  'Tébessa': { A_DOMICILE: 950, STOP_DESK: 550 },
  'Djelfa': { A_DOMICILE: 950, STOP_DESK: 550 },
  'Ouargla': { A_DOMICILE: 950, STOP_DESK: 550 },
  "El Oued": { A_DOMICILE: 950, STOP_DESK: 550 },
  'Ghardaïa': { A_DOMICILE: 950, STOP_DESK: 550 },
  'Ouled Djellal': { A_DOMICILE: 950, STOP_DESK: 550 },
  'Touggourt': { A_DOMICILE: 950, STOP_DESK: 550 },
  "El M'Ghair": { A_DOMICILE: 950, STOP_DESK: 550 },
  'El Menia': { A_DOMICILE: 950, STOP_DESK: 550 },
  'Timimoun': { A_DOMICILE: 1350, STOP_DESK: 900 },
  'Bordj Badji Mokhtar': { A_DOMICILE: 1350, STOP_DESK: 900 },
  'Béni Abbès': { A_DOMICILE: 1350, STOP_DESK: 900 },
  'Adrar': { A_DOMICILE: 1400, STOP_DESK: 900 },
  'Béchar': { A_DOMICILE: 1400, STOP_DESK: 900 },
  'El Bayadh': { A_DOMICILE: 1400, STOP_DESK: 900 },
  'Naâma': { A_DOMICILE: 1400, STOP_DESK: 900 },
  'In Salah': { A_DOMICILE: 1550, STOP_DESK: 1300 },
  'In Guezzam': { A_DOMICILE: 1550, STOP_DESK: 1300 },
  'Djanet': { A_DOMICILE: 1550, STOP_DESK: 1300 },
  'Tamanrasset': { A_DOMICILE: 1600, STOP_DESK: 1300 },
  'Illizi': { A_DOMICILE: 1600, STOP_DESK: 1300 },
  'Tindouf': { A_DOMICILE: 1600, STOP_DESK: 1300 },
};

export const getDeliveryCost = (wilaya: string, method: DeliveryMethod): number | null => {
  const rates = DELIVERY_RATES[wilaya as Wilaya];
  if (!rates) return null;
  return rates[method];
};
