-- Align orders with the COD multi-item checkout flow.
ALTER TABLE "Order" DROP COLUMN IF EXISTS "customerEmail";
ALTER TABLE "Order" DROP COLUMN IF EXISTS "customerPhone";
ALTER TABLE "Order" DROP COLUMN IF EXISTS "shippingAddress";
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "phone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "wilaya" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "baladia" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "address" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "subtotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT NOT NULL DEFAULT 'COD';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "confirmedAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "processingAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippedAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveredAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "cancelledAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "cancellationReason" TEXT;
CREATE INDEX IF NOT EXISTS "Order_wilaya_idx" ON "Order"("wilaya");

ALTER TABLE "OrderItem" RENAME COLUMN "productName" TO "productNameSnapshot";
ALTER TABLE "OrderItem" RENAME COLUMN "price" TO "unitPriceSnapshot";
ALTER TABLE "OrderItem" RENAME COLUMN "variantColor" TO "color";
ALTER TABLE "OrderItem" RENAME COLUMN "variantSize" TO "size";
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "fit" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "mockupFrontUrl" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "mockupBackUrl" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "designFrontUrl" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "designBackUrl" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "customizationJsonUrl" TEXT;
